# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Actions:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    #- name : Report jacoco
    #  run: mvn test -Pjacoco
      
    #- name : Report PIT
    #  run: mvn test -Ppit-test
      
    #- name : ba-dua report
    #  run: mvn test -Pba-dua-coverage

    #- name: Save Jacoco, Pit and Ba-dua Reports
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: Jacoco, Pit and Ba-dua Reports
    #    path: |
    #        target/site/jacoco
    #        target/pit-reports
    #        target/badua.xml
        
    - name: Build with Maven
      run: mvn test
      #run: mvn package
